name: New Badge
description: Submit a badge for the DevinsBadges Community Library
title: "[NEW] BADGENAME_HERE"
labels:
  - enhancements
assignees:
  - Intensed-dev

body:
  - type: input
    id: badge_name
    attributes:
      label: Badge Name
      description: Enter the name of the badge.
      placeholder: e.g. Modrinth
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe what the badge represents and what it should be used for.
      placeholder: Describe your badge...
    validations:
      required: true

  - type: textarea
    id: images
    attributes:
      label: Badge Images
      description: |
        Please upload both the PNG and SVG versions of the badge.

        You can drag and drop the files here.
      placeholder: |
        Please upload:
        - PNG
        - SVG
    validations:
      required: true

  - type: checkboxes
    id: styles
    attributes:
      label: Badge Styles
      description: Select all badge styles that should be included.
      options:
        - label: cozy
        - label: cozy minimal
        - label: compact
        - label: compact minimal
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Badge Category
      description: Select the category of the badge.
      options:
        - -- OTHER --
        - only available (community)
        - available
        - built with
        - built for
        - documentation
        - donate
        - requires
        - social
        - supported
        - translate
        - unsupported
      default: 1
    validations:
      required: true

  - type: input
    id: other_category
    attributes:
      label: Custom Category Name
      description: Only fill this out if you selected OTHER above.
      placeholder: e.g. featured
    validations:
      required: false
